# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: |
          echo "Workflow executed successfully"

      - name: Run build and test scripts
        run: |
          echo "Building and testing..."
          composer install || exit 1
          phpunit || exit 1

      - name: Deploy to production
        uses: digitalocean/do-deploy-v2
        env:
          DO_TOKEN: ${{ secrets.Web1097_hub }}
          DO_APP_NAME: LoanHub
          DO_ENVIRONMENT: production
        run: |
          echo "Deploying to production..."

      - name: Completion message
        run: |
          echo "Workflow completed successfully!"
